title: My first blog on Github webapge
author: Arti Sukasem
email: arti-sukasem@hotmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am learning github features

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
